### ISSUE TITLE
Topic starter - determine if other users can add items to the topic - maintain relevance and quality

### ISSUE THREAD

**Issue by Skiingseason** [sopra-fs24-group-05/sopra-fs24-group-05-server#12]
> As a user, I want to revise a topic and determine whether other users are allowed to add items to the topic so that I can control the contributions to the topics I create and maintain their relevance and quality.

**Estimate:** 8 hours

**Acceptance Criteria:**

- [x] When users create the topic, they should see an option to specify if other users are allowed to add items to this topic.
- [x] In the topic editing interface, users can toggle the setting.
- [x] When users browse a topic, there should be a permission status to show whether they have permission to add items to the topic.

**Comment by yimxia** [comment]
commit 889757755f1894e2ee581d80aaccf68ec3cad0ab
