### ISSUE TITLE
Administrator - detect duplicate items and merge - streamline the content and reduce ambiguity 

### ISSUE THREAD

**Issue by Skiingseason** [sopra-fs24-group-05/sopra-fs24-group-05-server#14]
> As a system administrator, I want the ranking system to detect duplicate items and merge items with synonyms within topics, so that the content is streamlined, and the integrity of topic rankings is maintained.

**Estimate:** 16 hours

**Acceptance Criteria:**

- [x] The system can automatically identify duplicate items within the same topic.
- [x] The system is equipped with a mechanism to recognize synonyms and merge such items, consolidating scores and comments to maintain discussion on the same item.
- [x] The ranking system recalculates scores and adjusts rankings accordingly after the merge.

**Comment by yimxia** [comment]
Add the function, commit 49ac9b9df3544354ba6e497e0ac1a5177744642f
