### ISSUE TITLE
User - be provided with translation - write comments in prefer language and easily read more comments

### ISSUE THREAD

**Issue by Skiingseason** [sopra-fs24-group-05/sopra-fs24-group-05-server#16]
> As a user, I want the app to provide a translation function so that I can write my comments in the language I want and easily read more comments written in different languages.

**Estimate:** 8 Hours

**Acceptance Criteria:**

- [x] A translation option is available below each comment and topic content.
- [x] Once click the translation option, the original text will be replaced by translated one, and an optional for displaying the original text will replace the translation option.

**Comment by yimxia** [comment]
commit ae67805af0d09eaffeed1dd5dfcfd10c0eb56157
