### ISSUE TITLE
User - topic filter - being able to explore possible topic of interest

### ISSUE THREAD

**Issue by Skiingseason** [sopra-fs24-group-05/sopra-fs24-group-05-server#18]
> As a user, I want the topic list to have filters and the ability to be ranked by heat, so that I can easily navigate and engage with topics of interest based on current trends and my preferences

**Estimate:** 8 Hours

**Acceptance Criteria:**

- [x] Users are provides with options to filter topics based on categories, tags, etc.
- [x] After the user chooses a filter, topics can be ranked by "hotness," a metric determined by engagement levels such as views, likes, comments, etc
- [x] Changes in filters or ranking preferences are reflected immediately in the topic list, ensuring users get information in real-time.

**Comment by yimxia** [comment]
commit 08277fa3f531fdbca1e0291f257b08ba56b64ba8
