### ISSUE TITLE
User - search topic - efficiently find topics of interest

### ISSUE THREAD

**Issue by Skiingseason** [sopra-fs24-group-05/sopra-fs24-group-05-server#19]
>I want to search for topics by keywords, with additional A-Z and # quick navigation options, so that I can efficiently find topics of interest.

**Estimate:** 16 Hours

**Acceptance Criteria:**

- [x] Users can input keywords into the search bar to find topics related to their interests.
- [x] Except for keyword search, an A-Z and # navigation feature is available, allowing users to quickly jump to topics starting with a specific letter or # (numbers and special symbolsincluded)
- [x] Ensure search results are relevant to the user's query, accurately reflecting the keywords or letter & # navigation.
- [x] Implement filters in the search function, allowing users to refine search results by criteria such as category, popularity, date, and user ratings.

**Comment by Skiingseason** [comment]
commit SHA: d0bd22ebefa8bd8dcb19baa567525b6012905a55

**Comment by yimxia** [comment]
commit 08277fa3f531fdbca1e0291f257b08ba56b64ba8
